export default {
  COLUMN: 4,
  FRUIT_SPAWN_TIME: 500,
  MAX_FRUIT_SPAWN: 40,
  GRAVITY: 9.8,
  START_LIVES_DEFAULT: 3,
  START_SCORE_DEFAULT: 0,
  CANVAS_HEIGHT: innerHeight,
  CANVAS_WIDTH: 500,
  SCORE_INCREMENT: 10,
  get COLUMN_WIDTH() {
    return this.CANVAS_WIDTH / this.COLUMN;
  },
} as const;
